### PR TITLE
Add non-illusionist gnome mages component

### PR DESCRIPTION
**Pull request by caillean7**
Component changes the values in the Gnome column of classes.2da for any mage classes from 2 to 1. Affects IWD1, BG1&2 installations. Tested on my local game installations. Path to GemRB installation must be passed to weidu or classes.2da has to be present in game override folder for it to work.

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Argh, look around — two spaces are used for indentation. :confounded:

**Comment by caillean7** [comment]
Sorry, couldn't really see that :P Started over.

**Comment by lynxlynxlynx** [comment]
It was at least better than the draft:
https://camo.githubusercontent.com/e09a164dd9bb64c111ce487ae9aafcf88495c498/687474703a2f2f692e696d6775722e636f6d2f764f574141554b2e706e67
:)

**Comment by caillean7** [comment]
Heh, tabs at least have the advantage that you can clearly make out if there are one or two. Or I need my eyes checked :S

**Comment by lynxlynxlynx** [comment]
I agree and gemrb uses them throughout, but here the style was set and mixing is the worst.

**Pull request closed without merging**
